name: Build Example

on:
  workflow_dispatch

jobs:
  build-example:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v5.0.0
    - name: Setup Node.js environment
      uses: actions/setup-node@v6.0.0 
    - name: Archive
      run: |
        rm -f app-bundle.zip
        zip -r app-bundle.zip . -x "*.git*" -x "app-bundle.zip"
    - name: Run tests
      run: |
        mkdir -p coverage
        npx jest --coverage --ci
    - name: Better Test Reports Action
      uses: mridang/action-test-reporter@v1.6.0
    - name: Verification
      run: ls -alhR
