name: Dependencies Example

on:
  workflow_dispatch

jobs:
  dependencies-example:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v5.0.0
    - name: Setup Node.js environment
      uses: actions/setup-node@v6.0.0 
    - name: Verification
      run: ls -alhR
